name: roggle
description: Simple, colorful and easy to expand logger for dart. Inspired by the logger and dependent to the logger.

version: 0.3.2
homepage: https://github.com/susatthi/roggle

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  logger: "2.0.2+1"
  meta:
  stack_trace:

dev_dependencies:
  coverage:
  pedantic_mono:
  test:
