name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Download dart sdk
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_CREDENTIALS_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_CREDENTIALS_REFRESH_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
